import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { Container, Typography } from '@mui/material';
import Title from '../components/Title';
import Main from '../components/Main';
import Card, { CardTitle, CardBody } from '../components/Card';
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <Container maxWidth="lg">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Main>
        <Title>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </Title>

        <Typography sx={{ margin: '4rem 0', lineHeight: 1.5, fontSize: '1.5rem', textAlign: 'center' }}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.tsx</code>
        </Typography>

        <div className={styles.grid}>
          <Card href="https://nextjs.org/docs">
            <CardTitle variant="h2">Documentation &rarr;</CardTitle>
            <CardBody>Find in-depth information about Next.js features and API.</CardBody>
          </Card>

          <Card href="https://nextjs.org/learn">
            <CardTitle variant="h2">Learn &rarr;</CardTitle>
            <CardBody>Learn about Next.js in an interactive course with quizzes!</CardBody>
          </Card>

          <Card href="https://github.com/vercel/next.js/tree/canary/examples">
            <CardTitle variant="h2">Examples &rarr;</CardTitle>
            <CardBody>Discover and deploy boilerplate example Next.js projects.</CardBody>
          </Card>

          <Card href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app">
            <CardTitle variant="h2">Deploy &rarr;</CardTitle>
            <CardBody>Instantly deploy your Next.js site to a public URL with Vercel.</CardBody>
          </Card>
        </div>
      </Main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </Container>
  )
}

export default Home
